
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
  {{- include "init.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end -}}
