kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageClassName }}
  labels:
  {{- include "init.labels" . | nindent 4 }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
